# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1068, 723)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_centralWidget = QtWidgets.QHBoxLayout()
        self.horizontalLayout_centralWidget.setObjectName("horizontalLayout_centralWidget")
        self.verticalLayout_sideBar = QtWidgets.QVBoxLayout()
        self.verticalLayout_sideBar.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_sideBar.setObjectName("verticalLayout_sideBar")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_sideBar.addWidget(self.pushButton)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_sideBar.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_sideBar.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_sideBar.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_sideBar.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_sideBar.addItem(spacerItem)
        self.horizontalLayout_centralWidget.addLayout(self.verticalLayout_sideBar)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_centralWidget.addWidget(self.line)
        self.verticalLayout_ChamberWidget = QtWidgets.QVBoxLayout()
        self.verticalLayout_ChamberWidget.setObjectName("verticalLayout_ChamberWidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_ChamberWidget.addWidget(self.textBrowser)
        self.DummyWidget = QtWidgets.QWidget(self.centralwidget)
        self.DummyWidget.setObjectName("DummyWidget")
        self.verticalLayout_ChamberWidget.addWidget(self.DummyWidget)
        self.horizontalLayout_centralWidget.addLayout(self.verticalLayout_ChamberWidget)
        self.gridLayout.addLayout(self.horizontalLayout_centralWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1068, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSelect_chamber = QtWidgets.QAction(MainWindow)
        self.actionSelect_chamber.setObjectName("actionSelect_chamber")
        self.actionConnect_to_server = QtWidgets.QAction(MainWindow)
        self.actionConnect_to_server.setObjectName("actionConnect_to_server")
        self.menuFile.addAction(self.actionSelect_chamber)
        self.menuFile.addAction(self.actionConnect_to_server)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Log In"))
        self.pushButton_5.setText(_translate("MainWindow", "Refresh Info"))
        self.pushButton_4.setText(_translate("MainWindow", "Modify Parameters"))
        self.pushButton_3.setText(_translate("MainWindow", "Scripts..."))
        self.pushButton_2.setText(_translate("MainWindow", "Other"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSelect_chamber.setText(_translate("MainWindow", "Select Chamber"))
        self.actionConnect_to_server.setText(_translate("MainWindow", "Connect to server"))
